[package]
name = "expense-tracker"
version = "0.5.2"
edition = "2024"
description = """
expense-tracker is a cli based tool to track expenses.
"""
readme = "README.md"
documentation = "https://github.com/purnamahesh/expense-tracker"
homepage = "https://github.com/purnamahesh/expense-tracker"
repository = "https://github.com/purnamahesh/expense-tracker"
keywords = ["expense", "tracker"]
categories = ["command-line-utilities", "utilities", "finance"]
license-file = "LICENSE"
exclude = [
  "/.github/",
  "/hooks/",
  "/.gitignore"
]
autotests = false
rust-version = "1.91.0"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
rstest = "0.26.1"
